dagbok/models.py
from sqlalchemy import Column, Integer, String, Text, DateTime
from database import Base
from datetime import datetime
import re

class Entry(Base):
    __tablename__ = 'entries'
    id = Column(Integer, primary_key=True)
    title = Column(String(100))
    slug = Column(String(100))
    summary = Column(String(250))
    body = Column(Text)
    pub_date = Column(DateTime)
    tags = Column(String(100))

    def __init__(self, title, summary, body, tags, pub_date=None):
        self.title = title
        self.summary = summary
        self.slug = re.sub('[^\w]+', '_', self.title.lower())
        self.body = body
        if pub_date is None:
            pub_date = datetime.now()
        self.pub_date = pub_date
        self.tags = tags

    def __repr__(self):
        return '<Post %r>' % self.title

dagbok/__init__.py
from flask import Flask, render_template, redirect, url_for, send_from_directory
from views.admin import admin
from models import Entry
from sqlalchemy.sql import extract

app = Flask(__name__)
app.config.from_pyfile('dagbok.cfg')
app.register_blueprint(admin, url_prefix='/admin')
app.debug = True

@app.route('/<path:resource>')
def serveStaticResource(resource):
    return send_from_directory('static/', resource)

@app.route('/')
def home():
    main_entry = Entry.query.order_by(Entry.pub_date.desc()).first()
    entries = Entry.query.order_by(Entry.pub_date.desc()).limit(4).offset(1)
    has_next = (Entry.query.count() > 5)
    next_page = 2
    return render_template('home.html', main_entry=main_entry, entries=entries,
                           has_next=has_next, next_page=next_page, title = 'Home')

@app.route('/page/<int:page_num>')
def page(page_num):
    if (page_num == 1):
        return redirect(url_for('home'))
    offset = 5 + ((page_num - 2) * 5)
    entries = Entry.query.order_by(Entry.pub_date.desc()).limit(5).offset(offset)
    has_next = (Entry.query.count() > (offset + 5))
    next_page = page_num + 1
    prev_page = page_num - 1
    return render_template('blog_list.html', entries=entries, has_next=has_next,
                           next_page=next_page, prev_page=prev_page, title = 'Blog')

@app.route('/<int:year>/<int:month>/<int:day>/<entry_slug>')
def get_entry(year, month, day, entry_slug):
    entry = Entry.query.filter(
        (extract('year', Entry.pub_date) == year) &
        (extract('month', Entry.pub_date) == month) &
        (extract('day', Entry.pub_date) == day)
        ).filter_by(slug=entry_slug).first()
    return render_template('single_entry.html', entry=entry)

dagbok/views/admin.py
from flask import Blueprint, render_template, request, current_app, session, \
     redirect, url_for
from dagbok.database import db_session
from dagbok.models import User, Entry

admin = Blueprint('admin', __name__)

@admin.route('/')
def index():
    if not session.get('logged_in'):
        return redirect(url_for('admin.login'))
    return render_template('admin.html')

@admin.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != current_app.config['USERNAME']:
            error = 'Invalid username'
        elif request.form['password'] != current_app.config['PASSWORD']:
            error = 'Invalid password'
        else:
            session['username'] = request.form['username']
            session['logged_in'] = True
            return redirect(url_for('admin.index'))
    return render_template('login.html', error=error)

@admin.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('show_entries'))

@admin.route('/post', methods=['GET', 'POST'])
def post_entry():
    if request.method == 'GET':
        return render_template('post_entry.html')
    if not session.get('logged_in'):
        abort(401)
    entry = Entry(request.form['title'], request.form['body'],
                  request.form['tags'])
    db_session.add(entry)
    db_session.commit()
    return redirect(url_for('home'))

dagbok/templates/admin.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}
<a href='/admin/post'>Post New Blog Entry</a>
  {% endif %}
{% endblock %}

dagbok/templates/blog_entry.html
{% extends "layout.html" %}
{% block body %}
<div>
{% if entry %}
    <p>{{ entry.title }}</p>
    <p>{{ entry.pub_date.strftime("%B %d, %Y") }}</p>
    <div><p>{{ entry.body|safe }}</p></div>
</div>
{% endif %}
{% endblock %}

dagbok/templates/blog_list.html
{% extends "layout.html" %}
{% block body %}
<div>
{% for entry in entries %}
<div>
    <p>{{ entry.title }}</p>
    <p>{{ entry.pub_date.strftime("%B %d, %Y") }}</p>
    <p>{{ entry.summary }}</p>
</div>
{% endfor %}
<a href='/page/{{ prev_page }}'>Previous Page</a>
{% if has_next %}
<a href='/page/{{ next_page }}'>Next Page</a>
{% endif %}
<hr />
</div>
{% endblock %}

dagbok/templates/blog_page.html
{% extends "layout.html" %}
{% block body %}
<div>
{% for entry in entries %}
<div>
    <p>{{ entry.title }}</p>
    <p>{{ entry.pub_date.strftime("%B %d, %Y") }}</p>
    <div class='entry_body' style="display:none"><p>{{ entry.body|safe }}</p></div>
    <div class='toggle'>View Entry</div>
</div>
{% endfor %}
<a href='/page/{{ prev_page }}'>Previous Page</a>
{% if has_next %}
<a href='/page/{{ next_page }}'>Next Page</a>
{% endif %}
<hr />
</div>
{% endblock %}

dagbok/templates/home.html
{% extends "layout.html" %}
{% block body %}
<div>
{% if main_entry %}
<div>
    <p><a href='/{{ main_entry.pub_date.strftime('%Y/%m/%d') }}/{{ main_entry.slug }}'>{{ main_entry.title }}</a></p>
    <p>{{ main_entry.pub_date.strftime("%B %d, %Y") }}</p>
    <p>{{ main_entry.body|safe }}</p>
</div>
{% endif %}
{% if entries %}
<hr />
<p class="prev">Previous Blog Entries</p>
{% for entry in entries %}
<div>
    <p><a href='/{{ entry.pub_date.strftime('%Y/%m/%d') }}/{{ entry.slug }}'>{{ entry.title }}</a></p>
    <p>{{ entry.pub_date.strftime("%B %d, %Y") }}</p>
    <p>{{ entry.summary }}</p>
</div>
{% endfor %}
{% endif %}
{% if has_next %}
<a href='/page/{{ next_page }}'>Next Page</a>
{% endif %}
</div>
{% endblock %}

dagbok/templates/layout.html
<!DOCTYPE HTML>
<html lang="en">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<head>
<title>{{ title }}</title>
</head>
<body>
<div>{% block body %}{% endblock %}</div>
</body>
</html>

dagbok/templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('admin.login') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
  </form>
{% endblock %}

dagbok/templates/post_entry.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}

<script type="text/javascript" src="//tinymce.cachefly.net/4.2/tinymce.min.js"></script>
<script type="text/javascript" >
tinyMCE.init({
        mode : "textareas"
});
</script >
    <form action="{{ url_for('admin.post_entry') }}" method=post class=add-entry>
      <dl>
        <dt>Entry Title:
        <dd><input type=text size=30 name=title>
	<dt>Summary:
        <dd><input type=text size=100 name=summary>
        <dt>Entry Content:
        <dd><textarea name=body rows=5 cols=40></textarea>
        <dt>Tags:
        <dd><input type=text size=30 name=tags>
	<dd><input type=submit value=Post>
      </dl>
    </form>
  {% endif %}
{% endblock %}

dagbok/templates/single_entry.html
{% extends "layout.html" %}
{% block body %}
<div>
{% if entry %}
    <p>{{ entry.title }}</p>
    <p>{{ entry.pub_date.strftime("%B %d, %Y") }}</p>
    <div><p>{{ entry.body|safe }}</p></div>
</div>
{% endif %}
{% endblock %}